CREATE DATABASE ECOMMERCE_PROJECT;

USE ECOMMERCE_PROJECT;
CREATE TABLE `PRODUTOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(1) NOT NULL DEFAULT 'A',
  `TITULO` varchar(255) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `VALORVENDA` float NOT NULL,
  `VALORCUSTO` float NOT NULL,
  `CATEGORIA` varchar(30) NOT NULL,
  `QUANTIDADE` int(11) NOT NULL,
  `DATACADASTRO` varchar(255) DEFAULT NULL,
  `IMAGEM` longblob DEFAULT NULL,
  `IMAGEM1` longblob DEFAULT NULL,
  `IMAGEM2` longblob DEFAULT NULL,
  `PESO` float DEFAULT NULL,
  `TAG` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `USUARIO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(1) NOT NULL DEFAULT 'A',
  `NOME` varchar(255) NOT NULL,
  `USUARIO` varchar(255) NOT NULL,
  `SENHA` varchar(255) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `TIPO` varchar(255) DEFAULT NULL,
  `DATANASC` varchar(10) NOT NULL,
  `CELULAR` varchar(14) DEFAULT NULL,
  `CPF` varchar(14) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  UNIQUE KEY `USUARIO` (`USUARIO`),
  UNIQUE KEY `SENHA` (`SENHA`),
  UNIQUE KEY `CPF` (`CPF`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4;

